### ISSUE TITLE
feedback API hangs and times out

### ISSUE THREAD

**Issue by rrjanbiah** [pennersr/shove#5] opened 2020-12-29 15:24 UTC
**Setup**: Using FCM alone with `shove` (with and without Redis)

```
curl -X POST 'http://x.x.x.x:8322/api/feedback'

curl: (7) Failed to connect to x.x.x.x port 8322: Connection timed out
```

**Comment by pennersr** [comment] 2020-12-29 19:18
This I cannot reproduce. For me:

```$ ./shove -api-addr 127.0.0.1:8322 -fcm-api-key xxxxxx```

... followed by:

```
$ curl -X POST 'http://localhost:8322/api/feedback'
{"feedback":[]}
```

... works just fine.

**Comment by pennersr** [comment] 2020-12-29 19:48
Closing -- likely a deployment issue.

**Closed by pennersr** 2020-12-29 19:48 UTC
